version: '3'
services:
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    links:
      - db-mysql
      - postgres
  db-mysql:
    image: mysql
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
  db-postgres:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: admin  